# this script has to be runned on github actions
# it runs every 30 minutes, every day, between 7 until 22 hours

name: cron1
on:
  schedule:
    - cron: "*/30 14-23 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call my API
        run:  |
          curl --request POST \
          --url "https://cl-aptos.tkwebdev.ca/api" \
          --header "Authorization: Bearer ${{secrets.CL_APTOS_PASSWORD}}"