# this script has to be runned on github actions
# it runs every 15 minutes, every day, between 8am until 4pm (both Vancouver time)

name: cron1
on:
  schedule:
    - cron: "*/15 16-23 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call my API
        run:  |
          curl --request POST \
          --url "https://home-seeker.tkwebdev.ca/api" \
          --header "Authorization: Bearer ${{secrets.CL_APTOS_PASSWORD}}"
