# in order to this file becomes a github actions, it needs 
# - to be placed in the current directory
# - .yaml extension

# in order to get the cron running after midnight, it needs to have a second cron for that
# the first cron runs until 23, and the second one starts at 0
# * 8 hours diff - UTC

name: cron1
on:
  schedule:
    # - cron: "*/15 16-23 * * *"
    - cron: "0,15,30,45 16-23 * * *" 
    ### ^^ Vancouver UTC-8 08:00 to 15:45, running every 15 minutes
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call my API
        run:  |
          curl --request POST \
          --url "https://home-seeker.tkwebdev.ca/api" \
          --header "Authorization: Bearer ${{secrets.CL_APTOS_PASSWORD}}"
